micronaut:
  application:
    name: Gloobus
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    cors:
      enabled: true
      configurations:
        allowedOrigins: http://localhost:4200


jackson:
  date-format: "yyyy-MM-dd'T'HH:mm:ssZ"

netty:
  default:
    allocator:
      max-order: 3

flyway:
  datasources:
    default:
      enabled: true

datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgres
    schema-generate: NONE
    dialect: POSTGRES
    jdbc-url: jdbc:postgresql://localhost:5222/postgres
    username: postgres
    password: postgres